version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/test/nen
    file_exists_behavior: OVERWRITE
hooks:
  AfterInstall:
    - location: scripts/after.sh
      timeout: 300
      runas: root
